<a href="https://colab.research.google.com/github/gakbn/ESCB-AngelGabrielAndradeAmezcua/blob/main/Untitled0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
#conjunto de datos
datos = {
      "usuario" : ["Ana", "Luis", "Martha", "Calorina", "Sofia", "Pedro", " Elena", "Diego"],
      "edad": [22,35,28,40,19,31,26,45],
      "ciudad": ["CDMX", "Monterrey", "Guadalajara", "Puebla", "Cancun", "Mérida", "Tijuana", "Yucatan" ],
      "compras_realizadas" :[5, 12,3,29,1,7,4,15],
      "activo" :[True, False, True, True, False, True, False, True],
      "fecha_registro" :["2026-01-10", "2026-01-12","2025-01-13", "2025-01-20","2026-02-10","2026-01-13","2026-01-25", "2026-01-12"],
}

In [ ]:
#Convertir Data frame
df = pd.DataFrame(datos)

In [ ]:
print(df)

    usuario  edad       ciudad  compras_realizadas  activo fecha_registro
0       Ana    22         CDMX                   5    True     2026-01-10
1      Luis    35    Monterrey                  12   False     2026-01-12
2    Martha    28  Guadalajara                   3    True     2025-01-13
3  Calorina    40       Puebla                  29    True     2025-01-20
4     Sofia    19       Cancun                   1   False     2026-02-10
5     Pedro    31       Mérida                   7    True     2026-01-13
6     Elena    26      Tijuana                   4   False     2026-01-25
7     Diego    45      Yucatan                  15    True     2026-01-12

In [ ]:
#Imprime los primeros 5 o especificamos
df.head()

    usuario  edad       ciudad  compras_realizadas  activo fecha_registro
0       Ana    22         CDMX                   5    True     2026-01-10
1      Luis    35    Monterrey                  12   False     2026-01-12
2    Martha    28  Guadalajara                   3    True     2025-01-13
3  Calorina    40       Puebla                  29    True     2025-01-20
4     Sofia    19       Cancun                   1   False     2026-02-10

In [ ]:
#Crear un dataframe con 10000000 de registro
cantidad = 1000000

In [ ]:
import random

In [ ]:
nombres = ["Ana", "Luis", "Martha", "Calorina", "Sofia", "Pedro", " Elena", "Diego"]
ciudades = ["CDMX", "Monterrey", "Guadalajara", "Puebla", "Cancun", "Mérida", "Tijuana", "Yucatan" ]
categoría = ["Tecnología", "Ropa", "Hogar", "Videojuegos", "Deportes", "Calzado", "Formal", "Deportivo"]

In [16]:
#Creación del DataFrame
dfMillon = pd.DataFrame ({
    "nombre" : [random.choice(nombres) for _ in range(cantidad)],
    "edad" : [random.randint(18,70) for _ in range(cantidad) ],
    "salario" : [round(random.uniform(5000,50000),2) for _ in range(cantidad)],
    "activo" : [random.choice([True, False]) for _ in range(cantidad)],
    "categoria" : [random.choice(ciudades) for _ in range(cantidad)],
    "anio_registro" : [random.randint(2020,2026) for _ in range(cantidad)]
})

In [17]:
dfMillon.dtypes

nombre            object
edad               int64
salario          float64
activo              bool
categoria         object
anio_registro      int64
dtype: object

In [20]:
dfMillon.memory_usage(deep=True)

Index                 132
nombre           54249578
edad              8000000
salario           8000000
activo            1000000
categoria        58005060
anio_registro     8000000
dtype: int64

In [21]:
dfMillon.memory_usage(deep=True).sum() / 1024**2

np.float64(130.89634895324707)

In [22]:
dfMillon.dtypes

nombre            object
edad               int64
salario          float64
activo              bool
categoria         object
anio_registro      int64
dtype: object

In [23]:
dfMillon.shape

(1000000, 6)