<a href="https://colab.research.google.com/github/gakbn/ESCB-AngelGabrielAndradeAmezcua/blob/main/Lab02.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [2]:
#conjunto de datos
datos = {
    "influencer" : ["@AnaCancun", "@LuisPlayas", "@MarthaTravel", "@CarolinaSol", "@SofiaRiviera", "@PedroMar", "@ElenaCaribe", "@DiegoAventura"],
    "likes": [1200, 3500, 2800, 4000, 1950, 3100, 2600, 4500],
    "comentarios": [45, 120, 34, 290, 15, 78, 42, 150],
    "fecha" :["2026-01-10", "2026-01-12", "2025-01-13", "2025-01-20", "2026-02-10", "2026-01-13", "2026-01-25", "2026-01-12"],
    "tipo_publicacion" :["foto", "reel", "carrusel", "historia", "foto", "reel", "historia", "carrusel"]
}

In [3]:
df = pd.DataFrame(datos)

In [4]:
print(df)

       influencer  likes  comentarios       fecha tipo_publicacion
0      @AnaCancun   1200           45  2026-01-10             foto
1     @LuisPlayas   3500          120  2026-01-12             reel
2   @MarthaTravel   2800           34  2025-01-13         carrusel
3    @CarolinaSol   4000          290  2025-01-20         historia
4   @SofiaRiviera   1950           15  2026-02-10             foto
5       @PedroMar   3100           78  2026-01-13             reel
6    @ElenaCaribe   2600           42  2026-01-25         historia
7  @DiegoAventura   4500          150  2026-01-12         carrusel

In [5]:
df.head()

      influencer  likes  comentarios       fecha tipo_publicacion
0     @AnaCancun   1200           45  2026-01-10             foto
1    @LuisPlayas   3500          120  2026-01-12             reel
2  @MarthaTravel   2800           34  2025-01-13         carrusel
3   @CarolinaSol   4000          290  2025-01-20         historia
4  @SofiaRiviera   1950           15  2026-02-10             foto

In [6]:
#Crear un dataframe con 10000000 de registro
cantidad = 1000000

In [7]:
import random

In [8]:
influencers = ["@AnaCancun", "@LuisPlayas", "@MarthaTravel", "@CarolinaSol", "@SofiaRiviera", "@PedroMar", "@ElenaCaribe", "@DiegoAventura"]
tipos = ["foto", "reel", "carrusel", "historia"]

In [10]:
# Creación del DataFrame
dfMillon = pd.DataFrame({
    "influencer" : [random.choice(influencers) for _ in range(cantidad)],
    "likes" : [random.randint(50, 50000) for _ in range(cantidad)],
    "comentarios" : [random.randint(0, 2000) for _ in range(cantidad)],
    "fecha" : [f"2026-0{random.randint(1,5)}-{random.randint(10,28)}" for _ in range(cantidad)],
    "tipo_publicacion" : [random.choice(tipos) for _ in range(cantidad)]
})

In [11]:
dfMillon.dtypes

influencer          object
likes                int64
comentarios          int64
fecha               object
tipo_publicacion    object
dtype: object

In [12]:
dfMillon.memory_usage(deep=True)

Index                    132
influencer          60748359
likes                8000000
comentarios          8000000
fecha               59000000
tipo_publicacion    54997196
dtype: int64

In [13]:
dfMillon.shape

(1000000, 5)